apiVersion: sonataflow.org/v1alpha08
kind: SonataFlowClusterPlatform
metadata:
  labels:
    app.kubernetes.io/name: sonataflowclusterplatform
    app.kubernetes.io/instance: sonataflowclusterplatform-sample
    app.kubernetes.io/part-of: sonataflow-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: sonataflow-operator
  name: sonataflowclusterplatform-sample
spec:
  # TODO(user): Add fields here
